{% set name = "cairocffi" %}
{% set version = "0.9.0" %}
{% set sha256 = "4600529463a8ece4bbdaf82e14a78769eaf143a8559e1b5469004f3fb8e7ff4d" %}

package:
  name: cairocffi
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Kozea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
 # patches:
 #   - dlopen-patch.linux.txt  # [linux]
 #   - dlopen-patch.osx.txt  # [osx]

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - cffi >=1.1.0
    - cairo 1.14.*
  run:
    - python
    - cffi >=1.1.0
    - cairo 1.14.*

test:
  imports:
    - cairocffi

about:
  home: https://github.com/SimonSapin/cairocffi
  license: BSD 3-Clause
  summary: 'cffi-based cairo bindings for Python'
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
