# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "B8A+o7vncbkUE/rJZJ1AXmDykAc+IiH0MASR+3Htc6BStF50OvdjEKMDGvpwPe0WKr3p52PQwbm92/8vhmdC3zpDuGOKMvBb7yBJGGP/4+j0j0p0d6ZOxfDYZoxEUGBjleTx182WR7EqsIk+JGsvkJyFSX6nu0+woU5BR8byAvsuwuxhTbTglSL95BxWzi3B/3QCSG/UZlMkQb5mamwFTA4i3NjwlHJAQ/QHt2RrxXAhlmJ+mNmUrh3QrScqsA1dr2IvOkgNChy+bdh6uMNlZyx+d30eh8KGZQhsmP3hUPvlFEnwfGrEd2WQtzDKWLkSUXk96yr6/mWlCSyi97OCykSHwSiYDBnUngdfazZpKqcP+i9NuF8W/7GeqD9g7GbE4VAS0+EQIOelfbPneqG32oNVipKagD6IVjsWCVK+S8AG4FNrOv14GLardO1TlxFq+Mkp3J0ECJzniIV8i/KLh2aVaHVzyikUoJss7/q6jm+BfgM/5gW1nvoQRBxd1b7jhwsXrMcDVmb8T3tHW0Qq1JGu/nNwNh4XIOyDOWqT9uB+aZ+qlhv2L7Xp8+3R2FXXBQsDZrSkhehGdHxTX+tS6dMZxbMehn/aeffDIJEqD6lwS2y3LAva5AMiV12/QMsFPyVQReXqrgm/nn9mDpImj33PHGwX1iYqz3yYduXb+gM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
