travis:
  secure:
    BINSTAR_TOKEN: B8A+o7vncbkUE/rJZJ1AXmDykAc+IiH0MASR+3Htc6BStF50OvdjEKMDGvpwPe0WKr3p52PQwbm92/8vhmdC3zpDuGOKMvBb7yBJGGP/4+j0j0p0d6ZOxfDYZoxEUGBjleTx182WR7EqsIk+JGsvkJyFSX6nu0+woU5BR8byAvsuwuxhTbTglSL95BxWzi3B/3QCSG/UZlMkQb5mamwFTA4i3NjwlHJAQ/QHt2RrxXAhlmJ+mNmUrh3QrScqsA1dr2IvOkgNChy+bdh6uMNlZyx+d30eh8KGZQhsmP3hUPvlFEnwfGrEd2WQtzDKWLkSUXk96yr6/mWlCSyi97OCykSHwSiYDBnUngdfazZpKqcP+i9NuF8W/7GeqD9g7GbE4VAS0+EQIOelfbPneqG32oNVipKagD6IVjsWCVK+S8AG4FNrOv14GLardO1TlxFq+Mkp3J0ECJzniIV8i/KLh2aVaHVzyikUoJss7/q6jm+BfgM/5gW1nvoQRBxd1b7jhwsXrMcDVmb8T3tHW0Qq1JGu/nNwNh4XIOyDOWqT9uB+aZ+qlhv2L7Xp8+3R2FXXBQsDZrSkhehGdHxTX+tS6dMZxbMehn/aeffDIJEqD6lwS2y3LAva5AMiV12/QMsFPyVQReXqrgm/nn9mDpImj33PHGwX1iYqz3yYduXb+gM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
