travis:
  secure:
    BINSTAR_TOKEN: l/1Q0g8oWEQOI1NpwDkd2pLwRPcMCbYqa1RPydkoH8m7wmRosYHWax1SPUkawFxcLI8J6kutjDtntuc5xrraYbSISEYeFQ8LH18YF/rwWsEfTg+X2uReaZk6WzZ+s8ETr8OUA9U/fJ9f0WNRf8aLNcfthzaJ4ypk9EldRy46Tj6FSMPApjlQLVzXOKYxelMb2osPEZRFIAShHVBrTOAPqkpMx4nn3csV5Jhg0yBIDjjmmQIkPg7ATuDluw0P6YHWfxvsPiBjMAnfvKM1k94vmJHRRka+1qIvWSbCCi+SnQK/ysqf3ZxuwVK+RS2PpgbBNCxmoocFcBADHgENxf9DrBKklt7PexBx53QGMGx6KE/8MC9DZP5p390bAqOYBpTMwzhKMKe2fnd0OmMT16n149Y9p3l1GkuABSPg/NoSGjsb80r2AriqYq5CUQJp9ROyXERlNWzWIbt5UGOzXT2wktraEI0k1vEk22S9tvjVNWBfOupuH801kYtIAabN4Ni7jPuo1fa1hrDe9tykBZwLdjABiNaidbidXeo1O70Z1lWjISoehXI17iTzPiz9aS65w066/PPg9QWK0pV3k8i7KeOFZiE8AUw0WQZMMB6JxDCLu/MGERwWAR5pUN1TG/4DMdllE1o2VeYUu7kmcNl5dAcmtjZdT7hr8QtP1wKcObU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
