appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: k3RRvM+CAkTZ2E+OX1urP+L0RAfUY6VsQLfh5Vrs/eTrgRrMFC0F1RMUtVlg5ByJEkUBStwBgAKE2127ObcObyVc0KW/AOvauekKZ83sUpVJEj114PDhuc9B7vSJsndPr2hCkkmmhbjgul61CDxM4OJvmL2N8WIkIP6gBWd2hqHKEE8b44B918o2S5vzJKaCnsz81pDDbZOdtxfhLjToKBcCwjIj/sFRs6bLJx1nESjuXe5WvZcVje9UHavWUoufp/suNf3d4Jlbiz/IvrJ+ay0lA0VYI0W/9AQUTTNzfZQ/QcII8FpB7ocL2PVkASF4tWShnzVkPaOr/K3D8Xfvg2Ed/p6WN2kom5i1dbFMrePsWucPs/Epj5x4W2NKLR0KfEelXOt+F78SF55dMMfRgDheXexCy8ArOunNrOfgdPKZL8PKNRl/si+szQhNyPu9S61F1a0F/8/8p1etgGy8O9VisY9gQC0ZwXMVxLLNOlPwF+V7wJWUHpiSONnB3GPl9Q35mpA3Y6pyrVw9k8PfVqazE3pTS4Bnq81DJnhkPDX/B16aMd4BG2NgE+JPR4tOXoU6udBnfufpDciDfh5bLq/kfAJHdJXaJcdQVW/wRR3NtZ84/F9n5eXg5jBNmdcO+Dxx8P46mFQJWiu31+HCGYhuYWUUnATa1UgyKB4mprk=}
provider:
  win: azure
conda_forge_output_validation: true
